baseurl = "https://kottn.me/"
languageCode = "ja"
title = "kottn.me"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = "UA-121050066-1"
#google_cse = "003631991625593988070:3jspqb_b6wi"

[params]
	# General information
	author = "kottn"
	description = "A CFD tech site."
	copyright = "kottn."

	# Repository
	#provider = "GitHub"
	#repo_url = "https://github.com/kottn"

	version = ""
	logo = "tentetenteeen.gif"
	favicon = "me-color.gif"

	permalink = "link"

	# Custom assets
	custom_css = [
	"img-circle.css",
	"design.css"
	]
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "teal"
    	accent  = "purple"

    [params.font]
    	text = "Ubuntu" # Roboto or Ubuntu
    	code = "Ubuntu Mono" # Roboto Mono or Ubuntu Mono


[social]
	twitter = "kottn_jp"
	github  = "kottn"
	email   = "kottn.jp@gmail.com"

[[menu.main]]
	name   = "Overview"
	url    = "/"
	weight = 0

[[menu.main]]
	name   = "Getting started"
	url    = "getting-started/"
	weight = 10

[[menu.main]]
	name   = "Adding content"
	url    = "adding-content/"
	weight = 20

[[menu.main]]
	name   = "Roadmap"
	url    = "roadmap/"
	weight = 30

[[menu.main]]
	name   = "License"
	url    = "license/"
	weight = 40

[blackfriday]
	smartypants = true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
