baseURL = "https://kottn.github.io/mypage"
languageCode = "ja"
title = "kottn.me"
hasCJKLanguage = true 
theme = "hugo-zen"
copyright = "2017 kottn."


[params]
logo    = "/logo/logo.png"
github  = "https://github.com/kottn/"
twitter = "https://twitter.com/kottn_jp"
