baseURL = "https://kottn.me/index.html"
title = "kottn.me"
theme = "nonblog"
uglyURLs = true
pygmentsCodefences = true
pygmentsUseClasses = true
googleAnalytics = "UA-121050066-1"
copyright = "(É”) 2017 kottn."

[author]
name = "kottn"
twitter = "@kottn_jp"

[params]
logo_src = "logo/kirin.png"
logo_alt = "LOGO"
theme_color = "#e08010"
google_cse = "003631991625593988070:3jspqb_b6wi"
og_image = "https://avatars.githubusercontent.com/kottn"

[taxonomies]
tag = "tags"


[[menu.main]]
    name = "R stats"
    identifier = "rstats"
    weight = 10

[[menu.main]]
    name = "Python"
    identifier = "python"
    weight = 20
